
services:
  postgis:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_kg_postgis'
    container_name: 'prge_kg_postgis'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5444:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data
volumes:
  postgis-local-data:

