x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=$(POSTGRES_USER)
  - &env-postgres-password POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)



services:
  postgis:
    image: kartoza/postgis:16-3.4
    container_name: postgis_arm-${{ENV_NAME}}
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data




volumes:
  postgis-local-data:
