x-environment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=$(POSTGRES_USER)
  - &env-postgres-password POSTGRES_PASSWORD=$(POSTGRES_PASSWORD)



services:
  postgis:
    image: kartoza/postgis:16-3.4
    container_name: postgis_arm
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5443:5432
    volumes:
      - postgis-local-data:/var/lib/postgresql/data


  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_2025-geoserver'
    container_name: 'prge_2025_geoserver'
    ports:
      - "9000:8080"
    volumes:
      - ..:/tmp/data:/opt/geoserver_data
      - ..:/.tmp/geoserver-config:/opt/geoserver/data_dir


  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi/Dockerfile
    image: 'prge_2025_fastapi'
    container_name: 'prge_2025_fastapi'
    ports:
      - 10000:10000




volumes:
  postgis-local-data:
